spring:
  datasource:
    url: jdbc:mysql://root:YzyxNrGmdomeYbOcTOYZEtVBEwpaGvpe@ballast.proxy.rlwy.net:47319/railway
    username: root
    password: YzyxNrGmdomeYbOcTOYZEtVBEwpaGvpe
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # none | validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081


